
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks-addons
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aws-samples/eks-blueprints-add-ons
    path: charts
    targetRevision: HEAD
    helm:
      releaseName: eks-addons
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
