apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: burnham
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/seb-demo/eks-blueprints-workloads
    path: teams/burnham
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: team-burnham
  syncPolicy:
    automated:
      prune: true
      selfHeal: true