
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks-workloads
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/seb-demo/eks-blueprints-workloads
    path: multi-repo/argo-app-of-apps/dev
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
